pipeline:
  build_book:
    image: node:8.11
    environment:
      - GA_CODE=UA-60024048-1
      - MIXPANEL_TOKEN=94fbb49ee4dd0cbee68e6a4c057d3ced
    commands:
      - npm i -g gitbook-cli
      - gitbook install
      - gitbook build
  test_build:
    image: alpine:3.7
    commands:
      - cat _book/index.html
  build_image:
    image: plugins/docker
    storage_driver: overlay
    secrets: [ docker_username, docker_password ]
    repo: kontena/pharos-docs
    tags:
      - ${DRONE_BRANCH}
    when:
      branch: ['2-1']
      event: ['push']
  deploy:
    image: quay.io/kontena/mortar:0.2
    pull: true
    secrets: [ kube_token, kube_ca, kube_server ]
    commands:
      - mortar fire -d --var "git_branch=${DRONE_BRANCH}" --var "build_number=${DRONE_BUILD_NUMBER}" _deploy/template/ "pharos-docs-${DRONE_BRANCH}"
    when:
      branch: ['2-1']
      event: ['push']