pipeline:
  build_book:
    image: node:8.11
    commands:
      - npm i -g gitbook-cli
      - gitbook install
      - gitbook build
  test_build:
    image: alpine:3.7
    commands:
      - cat _book/index.html
  build_image:
    image: plugins/docker
    storage_driver: overlay
    secrets: [ docker_username, docker_password ]
    repo: kontena/pharos-docs
    tags:
      - ${DRONE_BRANCH}