pipeline:
  build_book:
    image: node:8.11
    environment:
      - GA_CODE=UA-60024048-1
      - MIXPANEL_TOKEN=94fbb49ee4dd0cbee68e6a4c057d3ced
    commands:
      - npm i -g gitbook-cli
      - gitbook install
      - gitbook build
  test_build:
    image: alpine:3.7
    commands:
      - cat _book/index.html
  build_image:
    image: plugins/docker
    storage_driver: overlay
    secrets: [ docker_username, docker_password ]
    repo: kontena/pharos-docs
    tags:
      - ${DRONE_BRANCH}
    when:
      branch: ['master', '1-1', '1-2', '1-3']
      event: ['push']
  deploy:
    image: quay.io/kontena/mortar:latest
    pull: true
    secrets: [ kube_token, kube_ca, kube_server ]
    commands:
      - mortar -d --var "git_branch=${DRONE_BRANCH}" --var "build_number=${DRONE_BUILD_NUMBER}" "pharos-docs-${DRONE_BRANCH}" _deploy/template/
    when:
      branch: ['master', '1-1', '1-2', '1-3']
      event: ['push']
  default_ingress:
    image: quay.io/kontena/mortar:latest
    secrets: [ kube_token, kube_ca, kube_server ]
    commands:
      - mortar -d "pharos-docs-default-ingress" _deploy/ingress.yml
    when:
      branch: ['master']
      event: ['push']