kind: pipeline
name: default
steps:
  - name: build_book
    image: node:8.11
    environment:
      GA_CODE: UA-60024048-1
      MIXPANEL_TOKEN: 94fbb49ee4dd0cbee68e6a4c057d3ced
    commands:
      - npm i -g gitbook-cli
      - gitbook install
      - gitbook build
  - name: test_build
    image: alpine:3.7
    commands:
      - "cat _book/index.html | grep 'simple, solid, certified'"
  - name: build_image
    image: plugins/docker
    settings:
      storage_driver: overlay
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: kontena/pharos-docs
      tags:
        - ${DRONE_BRANCH}
    when:
      branch: ['2-3']
      event: ['push']
  - name: deploy
    image: quay.io/kontena/mortar:0.3
    pull: true
    environment:
      KUBE_TOKEN:
        from_secret: kube_token
      KUBE_CA:
        from_secret: kube_ca
      KUBE_SERVER:
        from_secret: kube_server
    commands:
      - mortar fire -d --var "git_branch=${DRONE_BRANCH}" --var "build_number=${DRONE_BUILD_NUMBER}" _deploy/template/ "pharos-docs-${DRONE_BRANCH}"
    when:
      branch: ['2-3']
      event: ['push']
